#! /bin/sh

set -e

id="$1"
if [ -z "$id" ]; then
    echo "Syntax: $0 ID"
    exit 1
fi

xml=/vmdisks/adhoc-cloud/"$id".xml

if [ ! -e "$xml" ]; then
    echo "Virtual machine $id doesn't exists!"
    exit 1
fi

virsh destroy "adhoc-cloud-$id" || true
virsh undefine "adhoc-cloud-$id"

trash=/vmdisks/adhoc-cloud/old/$(date +%s)
mkdir -p "$trash"
mv -n /vmdisks/adhoc-cloud/"$id".* "$trash"/

rm -f "/root/vnc-sockets/adhoc-cloud-$id" "/root/console-sockets/adhoc-cloud-$id"
