keys:
  - &hexa age1j3mkgedmeru63vwww6m44zfw09tg8yw6xdzstaq7ejfkvgcau40qwakm8x
  - &simon age17ez23w2kpxl0gcdx4ehcglkcfcfnv4qz0gq2n8ylxwx4yrtjpvjqxfasua
  - &dasJ age1lz3mvem0rgfxj7uavth8du4xsw23wp5ts77m5vvclxyj5mjxfujs0jgtcz
  - &mic92 age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz
  - &mic92-mac age1nnm255ah9wa4gpsaq0v023a75lnmlcxszt9lc6az3mtwzxgrucfq45rp7h
  - &nixos-foundation-macstadium-44911305-ofborg-org age1x608lllmu7gdfjnn6c8mvmmguft5f22fu7g38wv3ckmzqy2usq0q5u2ekx
  - &nixos-foundation-macstadium-44911362-ofborg-org age1d0u5ukkwsf47x4jv6uklcc4j3ljnmyz879syya2qneagz0t42cqqyf09dt
  - &nixos-foundation-macstadium-44911507-ofborg-org age1s0m24l3s29jr345uxk5j8zq7kd4sln3rvf0pdtd6afum3smtxsyqtjra0z
  - &nixos-foundation-macstadium-44911207-ofborg-org age1f6u77gvh94fk5fdh53lp04nk87cvjmwy2q3hjdlhd83mhlp0jg0s7rupux
  - &nixos-foundation-macstadium-44911104-ofborg-org age14gkxeqaehj2m38sesnc6fyd4c3hqjt7tqjz6q7lrult3uaahxcysdxt67n

creation_rules:
  - path_regex: secrets/nixos-foundation-macstadium-44911305.yml
    key_groups:
      - age:
          - *nixos-foundation-macstadium-44911305-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/nixos-foundation-macstadium-44911362.yml
    key_groups:
      - age:
          - *nixos-foundation-macstadium-44911362-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/nixos-foundation-macstadium-44911507.yml
    key_groups:
      - age:
          - *nixos-foundation-macstadium-44911507-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/nixos-foundation-macstadium-44911207.yml
    key_groups:
      - age:
          - *nixos-foundation-macstadium-44911207-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/nixos-foundation-macstadium-44911104.yml
    key_groups:
      - age:
          - *nixos-foundation-macstadium-44911104-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
