#!/usr/bin/env bash

PIDS=()

update() {
	local HOST=${1}
	local PROFILE=${2}
	(ssh "$HOST" -- sudo darwin-rebuild switch --flake "github:nixos/infra" 2>&1| sed -e "s/^/${HOST} | /") &
	PIDS+=($!)
}

update hetzner@enormous-catfish.mac.nixos.org
update hetzner@growing-jennet.mac.nixos.org
update hetzner@intense-heron.mac.nixos.org
update hetzner@maximum-snail.mac.nixos.org
update hetzner@sweeping-filly.mac.nixos.org
update customer@eager-heisenberg.mac.nixos.org
update customer@kind-lumiere.mac.nixos.org

wait "${PIDS[@]}"
