#!/usr/bin/env bash

PIDS=()

update() {
	local HOST=${1}
	local PROFILE=${2}
	(ssh "$HOST" -- sudo darwin-rebuild switch --flake "github:nixos/infra" 2>&1| sed -e "s/^/${HOST} | /") &
	PIDS+=($!)
}

update root@enormous-catfish.mac.nixos.org
update root@growing-jennet.mac.nixos.org
update root@intense-heron.mac.nixos.org
update root@maximum-snail.mac.nixos.org
update root@sweeping-filly.mac.nixos.org
update root@eager-heisenberg.mac.nixos.org
update root@kind-lumiere.mac.nixos.org
update root@norwegian-blue.mac.nixos.org
# ofborg (MacStadium)
update root@mac01.ofborg.org
update root@mac02.ofborg.org
update root@mac03.ofborg.org
update root@mac04.ofborg.org
update root@mac05.ofborg.org

wait "${PIDS[@]}"
