#! /bin/sh

set -e

id="$1"
if [ -z "$id" ]; then
    echo "Syntax: $0 ID" >&2
    exit 1
fi

info=/vmdisks/adhoc-cloud/"$id".info

if [ ! -e "$info" ]; then
    echo "Virtual machine $id doesn't exist!" >&2
    exit 1
fi

ipv6=$(cat "$info")
echo "$ipv6"
