keys:
  - &hexa age1j3mkgedmeru63vwww6m44zfw09tg8yw6xdzstaq7ejfkvgcau40qwakm8x
  - &zimbatm age1jrh8yyq3swjru09s75s4mspu0mphh7h6z54z946raa9wx3pcdegq0x8t4h
  - &caliban age1sv307kkrxwgjah8pjpap5kzl4j2r6fqr3vg234n7m32chlchs9lsey7nlq
  - &umbriel age15vcp7875xwtf64j4yshyld0a3hpgzv6n2kxky493s3q0swr9hdaqxugpv6
  - &staging-hydra age1vawam63mv097z4ae94tm2xlzkc66u3s87n7neu5jzm6687482u4sx8us3v
  - &m1-s age1v5qpkvs3zpz65gvfr2gv3ln7x6yfexvpregdr02hyvxnunu63ujqgwevf8
  - &mic92 age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz

creation_rules:
  - path_regex: secrets/[^/]+.caliban
    key_groups:
      - age:
          - *caliban
          - *hexa
          - *zimbatm

  - path_regex: secrets/[^/]+.umbriel
    key_groups:
      - age:
          - *umbriel
          - *hexa
          - *zimbatm

  # ssh keys used to bootstrap new machines
  - path_regex: secrets/[^/]+-hostkeys.yaml
    key_groups:
      - age:
          - *m1-s
          - *mic92

  - path_regex: secrets/[^/]+.staging-hydra
    key_groups:
      - age:
          - *staging-hydra
          - *m1-s
          - *mic92
