keys:
  - &hexa age1j3mkgedmeru63vwww6m44zfw09tg8yw6xdzstaq7ejfkvgcau40qwakm8x
  - &zimbatm age1jrh8yyq3swjru09s75s4mspu0mphh7h6z54z946raa9wx3pcdegq0x8t4h
  - &simon age17ez23w2kpxl0gcdx4ehcglkcfcfnv4qz0gq2n8ylxwx4yrtjpvjqxfasua
  - &caliban age1sv307kkrxwgjah8pjpap5kzl4j2r6fqr3vg234n7m32chlchs9lsey7nlq
  - &umbriel age15vcp7875xwtf64j4yshyld0a3hpgzv6n2kxky493s3q0swr9hdaqxugpv6
  - &staging-hydra age1zxcssfw5j6dwvcw25tmxs79lq40xk70h2s234hen8pkpte2qe30q9e7cy8
  - &mic92 age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz
  - &mic92-mac age1nnm255ah9wa4gpsaq0v023a75lnmlcxszt9lc6az3mtwzxgrucfq45rp7h
  - &Ericson2314 age1fgzf77gyah4efemnrqg4e7j0vk8fpq0uzrucepmdpsd5z7l4lgpsfq54df
  # ofborg admins
  - &dasJ age1lz3mvem0rgfxj7uavth8du4xsw23wp5ts77m5vvclxyj5mjxfujs0jgtcz
  # ofborg hosts
  - &core01-ofborg-org age1rrrj8tgcyp9xfxvy6zmk9487x62cgx0z68l7jretz2th6ey9nf4qh7nq7h
  - &eval01-ofborg-org age16d0phf8c5wy3rfsd4pgc42mqa3aw2llfukdhgu7pzklnzjr2rvxsusz842
  - &eval02-ofborg-org age1qn3q3y04pxumygmq96x0gk9qtrdcgdw4y5nl6xd780u4avk0qgsqy8tuu0
  - &eval03-ofborg-org age1yssfznyq8rljcpfthpulnvfls0l5t36fpqxkk5taxcwpkqhv9gcqrvvwh7
  - &eval04-ofborg-org age1vunut833rrdfulgnsjqtuke4yjtzexn2xqjqavwzxlgrg7n4y45qhurzwc
  - &build01-ofborg-org age1ulnex45wt7fpj92jy9c5del3ccz6mmnqptrsva24k8m7qsez9pcsdu3eae
  - &build02-ofborg-org age1wrp04f5c0d4jx3hwjsn8cyxdjzpzx6fl202zftqfvfdt7hx8efgskf6s86
  - &build03-ofborg-org age1n0yrvl2v397kztuhf00cdvrhf26c9uegwz6day8z9pyqj3zff4sq6ha0lm
  - &build04-ofborg-org age1l7xmxkh6y6d5svj06txknamlwdpfwac8855p3edgpu6jcqea7pvslw4r9a
  - &build05-ofborg-org age1mduqldqpqp33u2wwh685cwwkpj2ak36z67dtrq2tcskgqkultvps7w9q7u

creation_rules:
  - path_regex: secrets/[^/]+.caliban
    key_groups:
      - age:
          - *caliban
          - *hexa
          - *zimbatm
          - *mic92
          - *mic92-mac

  - path_regex: secrets/[^/]+.umbriel
    key_groups:
      - age:
          - *umbriel
          - *hexa
          - *zimbatm
          - *mic92
          - *mic92-mac

  # ssh keys used to bootstrap new machines
  - path_regex: secrets/[^/]+-hostkeys.yaml
    key_groups:
      - age:
          - *mic92
          - *mic92-mac
          - *hexa
          - *zimbatm
          - *staging-hydra

  - path_regex: secrets/[^/]+.staging-hydra
    key_groups:
      - age:
          - *staging-hydra
          - *mic92
          - *mic92-mac
          - *hexa
          - *zimbatm
          - *simon
          - *Ericson2314

  # ofborg
  - path_regex: secrets/[^/]+.core01.ofborg.org.yml
    key_groups:
      - age:
          - *core01-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/github-tokens.ofborg.org.yml
    key_groups:
      - age:
          - *core01-ofborg-org
          - *eval01-ofborg-org
          - *eval02-ofborg-org
          - *eval03-ofborg-org
          - *eval04-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/[^/]+.eval01.ofborg.org.yml
    key_groups:
      - age:
          - *eval01-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/[^/]+.eval02.ofborg.org.yml
    key_groups:
      - age:
          - *eval02-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/[^/]+.eval03.ofborg.org.yml
    key_groups:
      - age:
          - *eval03-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/[^/]+.eval04.ofborg.org.yml
    key_groups:
      - age:
          - *eval04-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/[^/]+.build01.ofborg.org.yml
    key_groups:
      - age:
          - *build01-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/[^/]+.build02.ofborg.org.yml
    key_groups:
      - age:
          - *build02-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/[^/]+.build03.ofborg.org.yml
    key_groups:
      - age:
          - *build03-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/[^/]+.build04.ofborg.org.yml
    key_groups:
      - age:
          - *build04-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
  - path_regex: secrets/[^/]+.build05.ofborg.org.yml
    key_groups:
      - age:
          - *build05-ofborg-org
          - *hexa
          - *simon
          - *dasJ
          - *mic92
          - *mic92-mac
