keys:
  - &hexa age1j3mkgedmeru63vwww6m44zfw09tg8yw6xdzstaq7ejfkvgcau40qwakm8x
  - &zimbatm age1jrh8yyq3swjru09s75s4mspu0mphh7h6z54z946raa9wx3pcdegq0x8t4h
  - &simon age17ez23w2kpxl0gcdx4ehcglkcfcfnv4qz0gq2n8ylxwx4yrtjpvjqxfasua
  - &caliban age1sv307kkrxwgjah8pjpap5kzl4j2r6fqr3vg234n7m32chlchs9lsey7nlq
  - &umbriel age15vcp7875xwtf64j4yshyld0a3hpgzv6n2kxky493s3q0swr9hdaqxugpv6
  - &staging-hydra age1xj4dl6xdl5ztmetp9axa0epjj922hu6a2gut3rrs5rdc5xv85yjsq5ggpx
  - &mic92 age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz
  - &mic92-mac age1nnm255ah9wa4gpsaq0v023a75lnmlcxszt9lc6az3mtwzxgrucfq45rp7h

creation_rules:
  - path_regex: secrets/[^/]+.caliban
    key_groups:
      - age:
          - *caliban
          - *hexa
          - *zimbatm
          - *mic92
          - *mic92-mac

  - path_regex: secrets/[^/]+.umbriel
    key_groups:
      - age:
          - *umbriel
          - *hexa
          - *zimbatm
          - *mic92
          - *mic92-mac

  # ssh keys used to bootstrap new machines
  - path_regex: secrets/[^/]+-hostkeys.yaml
    key_groups:
      - age:
          - *mic92
          - *mic92-mac
          - *hexa
          - *zimbatm
          - *staging-hydra

  - path_regex: secrets/[^/]+.staging-hydra
    key_groups:
      - age:
          - *staging-hydra
          - *mic92
          - *mic92-mac
          - *hexa
          - *zimbatm
          - *simon
