---
name: Apply DNS changes

on:
  push:
    branches:
      - main
    paths:
      - "dns/**"
  workflow_dispatch:

permissions: {}

jobs:
  dnscontrol:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31
      - name: dnscontrol push
        env:
          GANDI_TOKEN: "${{ secrets.GANDI_TOKEN }}" # Expires 2027-05-29
          GANDI_SHARING_ID: "${{ secrets.GANDI_SHARING_ID }}"
        working-directory: ./dns/
        run: |
          nix run --inputs-from . nixpkgs#dnscontrol -- push
