name: Check Terraform formatting

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check terraform/ formatting
      uses: dflook/terraform-fmt-check@v1
      with:
        path: terraform

    - name: Check terraform-iam/ formatting
      uses: dflook/terraform-fmt-check@v1
      with:
        path: terraform-iam
