name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - flake.lock
  pull_request:
    paths:
      - ".github/**"
      - flake.lock

permissions: {}

jobs:
  zizmor:
    name: Run zizmor against GitHub Action workflows
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Install nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31

      - name: Run zizmor 🌈
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix run --inputs-from . nixpkgs-unstable#zizmor -- \
            --format sarif --pedantic . > results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4
        with:
          sarif_file: results.sarif
          category: zizmor
