name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - flake.lock
  pull_request:
    paths:
      - ".github/**"
      - flake.lock

permissions: {}

jobs:
  zizmor:
    name: Run zizmor against GitHub Action workflows
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install nix
        uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31

      - name: Run zizmor 🌈
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix run --inputs-from . nixpkgs-unstable#zizmor -- \
            --format sarif --pedantic . > results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@b1bff81932f5cdfc8695c7752dcee935dcd061c8 # v4
        with:
          sarif_file: results.sarif
          category: zizmor
